name: natural_remedies_app
description: Offline-first mobile learning app for natural remedies (Flutter + TFLite)
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"

# --- Versions are pinned with ^ (caret) to track compatible updates ---
dependencies:
  flutter:
    sdk: flutter

  # iOS-like visuals, navigation, state, i18n
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  google_fonts: ^6.2.1    # Inter on Android; SF on iOS stays system

  # Offline data, paths
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

  # On-device ML
  tflite_flutter: 0.11.0

  # UI niceties
  flutter_svg: ^2.0.10
  transparent_image: ^2.0.1
  animations: ^2.0.11
  share_plus: ^12.0.0
  path: ^1.9.1
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11   # needed later if you generate code (e.g., Hive adapters)

flutter:
  uses-material-design: true
  assets:
    - assets/corpus/en/
    - assets/corpus/sw/
    - assets/ml/mobilebert_qa_float32.tflite
    - assets/ml/vocab.txt